name: pr-validation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
  release-build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    env:
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add $TARGET
      - run: cargo build --release --target $TARGET
      - run: |
          (cd target/$TARGET/release && tar -czvf souper-$TARGET.tar.gz souper)
