name: pr-validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
      - name: install clippy
        run: rustup component add clippy
      - name: lint
        run: cargo clippy -- -D warnings
      - name: fmt
        run: cargo fmt --check
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: install cargo-binstall
        run: |
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
          tar -xvf cargo-binstall-x86_64-unknown-linux-musl.tgz
      - name: install cargo-tarpaulin
        run: ./cargo-binstall --no-confirm cargo-tarpaulin
      - name: verify coverage
        run: cargo tarpaulin --fail-under 68
