name: pr-validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
      - name: install clippy
        run: rustup component add clippy
      - name: lint
        run: cargo clippy -- -D warnings
      - name: fmt
        run: cargo fmt --check
      - name: test coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --fail-under 68
