name: pr-validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
      - name: install clippy
        run: rustup component add clippy
      - name: lint
        run: cargo clippy -- -D warnings
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add x86_64-pc-windows-msvc
      - run: cargo build --release --target x86_64-pc-windows-msvc
      - run: |
          ls target/x86_64-pc-windows-msvc/release
          compress-archive -path "target/x86_64-pc-windows-msvc/release/souper.exe" "target/x86_64-pc-windows-msvc/release/souper-x86_64-pc-windows-msvc.zip" -compressionlevel optimal
          ls target/x86_64-pc-windows-msvc/release
