name: release

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1

  release-build:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    env:
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - run: rustup target add $TARGET
      - run: cargo build --release --target $TARGET
      - run: (cd target/${TARGET}/release && tar -czvf souper-${TARGET}.tar.gz souper)
      - run: |
          TAG=$(echo ${{ github.ref }} | sed 's#refs/tags/##')
          gh release upload $TAG target/${TARGET}/release/souper-${TARGET}.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
